export const DEMO_CATEGORIES = ['Remeras', 'Buzos', 'Pantalones', 'Accesorios'];

export const DEMO_PRODUCTS = [
  {
    nombre: 'Remera básica algodón',
    precio: 8500,
    categoria: 'Remeras',
    stockMinimo: 3,
    colores: ['Blanco', 'Negro'],
    variants: [
      { talle: 'S', color: 'Blanco', cantidad: 6 },
      { talle: 'M', color: 'Blanco', cantidad: 5 },
      { talle: 'L', color: 'Blanco', cantidad: 4 },
      { talle: 'S', color: 'Negro', cantidad: 5 },
      { talle: 'M', color: 'Negro', cantidad: 4 },
      { talle: 'L', color: 'Negro', cantidad: 3 },
    ],
    cantidad: 27,
  },
  {
    nombre: 'Remera oversize unisex',
    precio: 11900,
    categoria: 'Remeras',
    stockMinimo: 3,
    colores: ['Gris', 'Verde'],
    variants: [
      { talle: 'M', color: 'Gris', cantidad: 4 },
      { talle: 'L', color: 'Gris', cantidad: 3 },
      { talle: 'M', color: 'Verde', cantidad: 3 },
      { talle: 'L', color: 'Verde', cantidad: 2 },
    ],
    cantidad: 12,
  },
  {
    nombre: 'Buzo canguro classic',
    precio: 24500,
    categoria: 'Buzos',
    stockMinimo: 4,
    colores: ['Azul', 'Gris'],
    variants: [
      { talle: 'S', color: 'Azul', cantidad: 2 },
      { talle: 'M', color: 'Azul', cantidad: 2 },
      { talle: 'L', color: 'Gris', cantidad: 2 },
    ],
    cantidad: 6,
  },
  {
    nombre: 'Buzo con capucha premium',
    precio: 29900,
    categoria: 'Buzos',
    stockMinimo: 4,
    colores: ['Negro'],
    variants: [
      { talle: 'M', color: 'Negro', cantidad: 1 },
      { talle: 'L', color: 'Negro', cantidad: 1 },
    ],
    cantidad: 2,
  },
  {
    nombre: 'Campera rompevientos',
    precio: 36000,
    categoria: 'Buzos',
    stockMinimo: 3,
    colores: ['Rojo', 'Negro'],
    variants: [
      { talle: 'S', color: 'Rojo', cantidad: 2 },
      { talle: 'M', color: 'Rojo', cantidad: 3 },
      { talle: 'L', color: 'Negro', cantidad: 3 },
    ],
    cantidad: 8,
  },
  {
    nombre: 'Jean skinny',
    precio: 28000,
    categoria: 'Pantalones',
    stockMinimo: 3,
    colores: ['Azul'],
    variants: [
      { talle: '38', color: 'Azul', cantidad: 5 },
      { talle: '40', color: 'Azul', cantidad: 6 },
      { talle: '42', color: 'Azul', cantidad: 4 },
    ],
    cantidad: 15,
  },
  {
    nombre: 'Jean cargo',
    precio: 32500,
    categoria: 'Pantalones',
    stockMinimo: 3,
    colores: ['Negro', 'Beige'],
    variants: [
      { talle: '40', color: 'Negro', cantidad: 3 },
      { talle: '42', color: 'Negro', cantidad: 3 },
      { talle: '40', color: 'Beige', cantidad: 2 },
      { talle: '42', color: 'Beige', cantidad: 2 },
    ],
    cantidad: 10,
  },
  {
    nombre: 'Jogging corderito',
    precio: 19800,
    categoria: 'Pantalones',
    stockMinimo: 4,
    colores: ['Gris'],
    variants: [{ talle: 'M', color: 'Gris', cantidad: 1 }],
    cantidad: 1,
  },
  {
    nombre: 'Short deportivo',
    precio: 12400,
    categoria: 'Pantalones',
    stockMinimo: 3,
    colores: ['Negro', 'Azul'],
    variants: [
      { talle: 'S', color: 'Negro', cantidad: 3 },
      { talle: 'M', color: 'Negro', cantidad: 3 },
      { talle: 'M', color: 'Azul', cantidad: 3 },
    ],
    cantidad: 9,
  },
  {
    nombre: 'Gorra urbana',
    precio: 9900,
    categoria: 'Accesorios',
    stockMinimo: 2,
    variants: [],
    cantidad: 0,
  },
  {
    nombre: 'Medias deportivas (par)',
    precio: 3200,
    categoria: 'Accesorios',
    stockMinimo: 10,
    variants: [],
    cantidad: 40,
  },
  {
    nombre: 'Cinturón cuero',
    precio: 7800,
    categoria: 'Accesorios',
    stockMinimo: 3,
    variants: [],
    cantidad: 6,
  },
];